---
title: "correlation_matrix"
format: html
---

# Load Packages

```{r}
library(polycor)
library(corrplot)
library(readr)
library(here)
library(tidyverse)
```

# Load Data

```{r}
clinical_sample <- read.delim(here("data", "data_clinical_sample.txt"), sep = "\t", skip = 4, header = TRUE)

mutations <- read.delim(here("data", "data_mutations.txt"), sep = "\t", header = TRUE)

clinical_patient <- read.delim(here("data", "data_clinical_patient.txt"), sep = "\t", skip = 4, header = TRUE)
```

# Clean Data

```{r}
colnames(clinical_patient)
```

```{r}
patient_clean <- clinical_patient |> select(-c(AGE_GROUP))
sample_clean <- clinical_sample |>
  select(c(PATIENT_ID, SAMPLE_ID,CANCER_TYPE, TMB_NONSYNONYMOUS, AGE_AT_SEQ_REPORT) )
mutation_clean <- mutations |>
  select(c(Variant_Classification, Tumor_Sample_Barcode))|>
  group_by(Tumor_Sample_Barcode)|>
  summarise(n_mutations = n())|>
  rename('SAMPLE_ID' = Tumor_Sample_Barcode)

patient_sample <- patient_clean |> left_join(sample_clean, by = 'PATIENT_ID')
patient_sample_mutations <- patient_sample |> left_join(mutation_clean, by = 'SAMPLE_ID')
```

How many mutations per sample

```{r}
mutations |> group_by(Tumor_Sample_Barcode)|>
  summarise(n= n())|>
  ggplot(aes(n))+
  geom_bar()
```

# Creating Correlation Matrix

```{r}
analysis_data <- patient_sample_mutations |> 
  select(-c(PATIENT_ID, SAMPLE_ID))|>
  mutate_if(is.character, as.factor)

correlation_matrix<- hetcor(analysis_data)

corrplot(correlation_matrix$correlations, method="color", tl.col="black", tl.srt=45)
  



```

\
