---
title: "Importing Raw data"
format: html
editor: visual
---

# Load Libraries

```{r}
library(here)
```

# Download raw data

```{r}
folder <- here('raw')
local_path <- file.path(folder, 'raw_data.tar.gz')

```

```{r}
if (!dir.exists(folder)) {
  dir.create(folder, recursive = TRUE)
}
download.file('https://cbioportal-datahub.s3.amazonaws.com/tmb_mskcc_2018.tar.gz', local_path, mode = 'wb')
```

# Unpack raw data

```{r}
untar(
  tarfile = local_path,
  exdir = folder
)
```

# Load Data

```{r}
clinical_sample <- read.delim(file.path(folder, "tmb_mskcc_2018/data_clinical_sample.txt"), sep = "\t", skip = 4, header = TRUE)

mutations <- read.delim(file.path(folder, "tmb_mskcc_2018/data_mutations.txt"), sep = "\t", header = TRUE)

clinical_patient <- read.delim(file.path(folder, "tmb_mskcc_2018/data_clinical_patient.txt"), sep = "\t", skip = 4, header = TRUE)

gene_panel_matrix <- read.delim(file.path(folder, "tmb_mskcc_2018/data_gene_panel_matrix.txt"), sep = "\t")

raw_data_sv <- read.delim(file.path(folder, "tmb_mskcc_2018/data_sv.txt"),sep = '\t')
```

TODO:

-   clean data of mutations(Louis)
