---
title: "logistic_regression"
format: 
  html:
    self-contained: true
---

# Load Libraries

```{r}
library(readr)
library(here)
library(tidyverse)
```

# Load Data

```{r}
patient_sample <- read_tsv(file = here('data','patient_sample_gene_panel.tsv'))
sv <- read_tsv(file = here('data','sv.tsv'))
mutations <- read_tsv(file = here('data','data_mutation_cleaned.tsv'))
```

# Data Wrangling

```{r}
mutation_counts <- mutations |>
  select(c(Variant_Classification, Tumor_Sample_Barcode))|>
  group_by(Tumor_Sample_Barcode)|>
  summarise(n_mutations = n())|>
  rename('SAMPLE_ID' = Tumor_Sample_Barcode)

patient_sample_mutations <- patient_sample |>
  select(c(PATIENT_ID, SAMPLE_ID,CANCER_TYPE, TMB_NONSYNONYMOUS, AGE_AT_SEQ_REPORT, TUMOR_PURITY, SEX,OS_MONTHS, OS_STATUS, DRUG_TYPE, SAMPLE_TYPE, SAMPLE_COVERAGE))|>
  left_join(mutation_counts, by = 'SAMPLE_ID')
```

# Fit Model

We want to see if the survival is influenced by any of the variables.

```{r}
model <- glm(Survival ~.,family=binomial(link='logit'),data=analysis_data)

summary(model)
```

Here no variable seems to have a big influence

```{r}
anova(model, test="Chisq")
```

Here multiple variables are marked as significance

[Source: https://www.r-bloggers.com/2015/09/how-to-perform-a-logistic-regression-in-r/](https://www.r-bloggers.com/2015/09/how-to-perform-a-logistic-regression-in-r/)
