---
title: "Survival Analysis"
format: html
editor: visual
---

# Library import

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(purrr)
library(survival)
library(broom)
```

# Data import

```{r}
clinical_sample <- read.delim(here("data", "data_clinical_sample.txt"), sep = "\t", skip = 4, header = TRUE)

mutations <- read.delim(here("data", "data_mutation_cleaned"), sep = "\t", header = TRUE)

clinical_patient <- read.delim(here("data", "data_clinical_patients_clean.tsv"), sep = "\t", header = TRUE)
```

# Data wrangling

Need sex, age, cancer type to be transformed to numerical categories

```{r}
new_clinical_sample <- clinical_sample |> 
  select(c(1,2,3,4,11)) |> 
  drop_na()

clinical_patient <- clinical_patient |> 
  rename(PATIENT_ID = Patient_ID)

df <- clinical_patient |> 
  left_join(new_clinical_sample) |> 
  mutate(TUMOR_PURITY = as.numeric(TUMOR_PURITY),
         CANCER_TYPE = as.factor(CANCER_TYPE)) |> 
  drop_na()
```

# Kaplan-Meier curve

```{r}
patients$Survival_Months <- as.numeric(patients$Survival_Months)

KM_f <- survfit(Surv(Survival_Months, OS_status) ~1, data = patients)

#convert to a tibble

tibble_KM_f <- tibble(
  time = KM_f$time,
  survival = KM_f$surv)

ggplot(tibble_KM_f, 
       mapping = aes(x = time,
                     y = survival))+
  geom_line()+
  labs(title = 'Overall Survival rate of the patients')
```

# Cox regression

Cox regression for hazard analysis

```{r}
cancer_types <- df |> 
  select(CANCER_TYPE) |> 
  distinct()

print("The different cancer types are:")
cancer_types
```

```{r}
cox_model_cancer_type <- coxph(Surv(Survival_Months, OS_status) ~ CANCER_TYPE, data = df)
summary(cox_model_cancer_type)
```

```{r}
surv_fit_cancer_type <- survfit(cox_model_cancer_type)

surv_fit_cancer_type_tidy <- surv_fit_cancer_type |> 
  tidy()

plt0 <- surv_fit_cancer_type_tidy |> 
  ggplot(
    aes(x = time,
        y = estimate)
  ) + 
  geom_step() +
  labs(
    title = "Survival Curves from Cox Model Prediction",
    x = "Time",
    y = "Survival Probability"
  ) + 
  theme_classic() 

plt0
```

```{r}
cox_model_purity <- coxph(Surv(Survival_Months, OS_status) ~ TUMOR_PURITY, data = df)
summary(cox_model_purity)
```

```{r}
surv_fit <- survfit(cox_model_tot)

surv_fit_tidy <- surv_fit |> 
  tidy()

plt1 <- surv_fit_tidy |> 
  ggplot(
    aes(x = time,
        y = estimate)
  ) + 
  geom_step() +
  labs(
    title = "Survival Curves from Cox Model Prediction",
    x = "Time",
    y = "Survival Probability"
  ) + 
  theme_classic() 

plt1
```
